### ISSUE TITLE
Colors not changing as expected

### ISSUE THREAD

**Issue by gabs712** [luckasRanarison/tailwind-tools.nvim#53]
**Describe the bug**
When changing the colorscheme, after running :colorscheme,  the completion icons for colors become greyed out.

**Initial colorscheme (tokyonight)**
![before](https://github.com/user-attachments/assets/1989f58e-f98d-41ba-9f8b-45af38483c4e)

**After change (catppuccin)**
![after](https://github.com/user-attachments/assets/d8a4de4f-9025-410e-ace1-2bc963dfd1b9)

The same also happens with any other colorschemes that i've tried out.
I'm using neovim v0.11.0.

**Comment by luckasRanarison** [comment]
It should be fixed now

**Comment by gabs712** [comment]
Great! Just one more thing: i've also noticed that the issue persists with the little concealing icon.

**Comment by luckasRanarison** [comment]
Nice catch, changing colorscheme breaks highlights

**Comment by luckasRanarison** [comment]
Fixed
